---
title: "Two Parameters"
format: html
execute: 
  echo: false
---

```{r}
#| message: FALSE
library(tidyverse)
library(primer.data)
library(ggplot2)
library(brms)
library(tidybayes)
library(gtsummary)
library(NHANES)

```

```{r}
nhanes |> filter(sex == "Male", age >= 18) |> select(height) |> drop_na() |> ggplot(aes(x = height))+
geom_histogram(bins = 50)+
labs(title = "Male Adult Height in 2009", x = "Height (cm)", y = "Count", caption = "Source: National Health and Nutrition Examination Survey")
```
```{r}
#| cache: TRUE
fit_male_height<- brm(formula = height ~ 1, data = ch5, family = gaussian(), silent = 2, refresh = 0, seed = 12)
```


```{r}
ndata <- tibble(.rows = 1)
fit_male_height |> add_predicted_draws(newdata = ndata) |> ggplot(aes(x = .prediction))+
geom_histogram(aes(y = after_stat(count/sum(count))), bins = 100) +
labs(title = "Probability of a man being taller than 180 centimenters", x = "Height", y = "Probability")+
scale_x_continuous( labels = scales::number_format())+
scale_y_continuous(labels = scales::percent_format(accuracy = 1))
```

I used the nhanes data set from the National Health and Nutrition Examination Survey to find the height of Americans males. A problem that casts doubt on this is if we want to include the heights of people with disability. Then I calculated the proportion of people with a height of over 180 cm.
```{r}
tbl_regression(fit_male_height, intercept = TRUE)

```

```{r}
fit_male_height |> add_predicted_draws(newdata = ndata) |> mutate(tall = if_else(.prediction > 180, TRUE, FALSE )) |> summarize(odds = mean(tall))
```

